/**
 * Brand Tokens sampled directly from the official Bakala Express identity.
 * Generated by scripts/build-brand-assets.mjs
 */
export const brand = {
  /** Median pepper body fill color (#009225) - Vibrant accent, icons, decorative borders */
  green: '#009225',
  /** Dark green stroke & stem (#005E25) - Accessible button backgrounds with white text (WCAG 7.99:1), links, high-contrast text */
  greenDark: '#005E25',
  /** Primary typography black (#000000) */
  black: '#000000',
  /** Clean canvas white (#FFFFFF) */
  white: '#FFFFFF',
  /** Muted secondary neutral (#6B6B6B) */
  muted: '#6B6B6B',
} as const;

export type BrandColors = typeof brand;
