/**
 * Brand Tokens sampled directly from the official Bakala Express identity.
 * Generated by scripts/build-brand-assets.mjs
 */
export const brand = {
  /** Primary vibrant emerald green from Behance reference (#157B42) */
  green: '#157B42',
  /** Accessible primary button green (#157B42) */
  greenDark: '#157B42',
  /** Secondary highlight orange from Behance reference (#FF6A1A) */
  orange: '#FF6A1A',
  /** Primary typography dark neutral (#1A1A1A) */
  black: '#1A1A1A',
  /** Clean canvas white (#FFFFFF) */
  white: '#FFFFFF',
  /** Secondary muted typography (#575757) */
  muted: '#575757',
  /** Canvas background (#FAFAFA) */
  background: '#FAFAFA',
} as const;

export type BrandColors = typeof brand;
